import { z } from "zod";

/** Place autocomplete against the external provider (admin, billed). */
export const PlaceAutocompleteQuerySchema = z.object({
  q: z
    .string()
    .trim()
    .min(2, "Search query must be at least 2 characters.")
    .max(200, "Search query cannot exceed 200 characters."),

  limit: z.coerce.number().int().min(1).max(20).default(10),

  /**
   * Groups a run of keystrokes plus the final details call into one billed
   * session. Opaque to Kizunia — generated by the client, passed straight
   * through.
   */
  sessionToken: z.string().trim().max(100).optional(),
});

export type PlaceAutocompleteQuery = z.infer<typeof PlaceAutocompleteQuerySchema>;

/** Typeahead over search areas the platform already knows (public, free). */
export const SearchAreaQuerySchema = z.object({
  q: z
    .string()
    .trim()
    .min(2, "Search query must be at least 2 characters.")
    .max(200, "Search query cannot exceed 200 characters."),

  limit: z.coerce.number().int().min(1).max(20).default(10),
});

export type SearchAreaQuery = z.infer<typeof SearchAreaQuerySchema>;
