export const CompetitionErrorCode = {
    NOT_FOUND: "COMPETITION_NOT_FOUND",

    DUPLICATE_SLUG: "COMPETITION_DUPLICATE_SLUG",

    DELETED: "COMPETITION_DELETED",

    ARCHIVED: "COMPETITION_ARCHIVED",

    LOCATION_NOT_FOUND: "COMPETITION_LOCATION_NOT_FOUND",

    LOCATION_LIMIT_REACHED: "COMPETITION_LOCATION_LIMIT_REACHED",

    LOCATION_REORDER_MISMATCH: "COMPETITION_LOCATION_REORDER_MISMATCH",

    LOCATION_SOURCE_MISSING: "COMPETITION_LOCATION_SOURCE_MISSING",

    LOCATION_PROVIDER_UNAVAILABLE: "COMPETITION_LOCATION_PROVIDER_UNAVAILABLE",

    LOCATION_RESOLUTION_FAILED: "COMPETITION_LOCATION_RESOLUTION_FAILED",


} as const;

export type CompetitionErrorCode =
    (typeof CompetitionErrorCode)[keyof typeof CompetitionErrorCode];