export enum PlatformAction {
  CREATE_COMPETITION = "CREATE_COMPETITION", //TODO: change to competition
  VIEW_ALL_COMPETITIONS = "VIEW_ALL_COMPETITIONS",
  MANAGE_USERS = "MANAGE_USERS",

  ACCESS_ADMIN_DASHBOARD = "ACCESS_ADMIN_DASHBOARD",

  // Users
  VIEW_ALL_USERS = "VIEW_ALL_USERS",

  // Projects
  VIEW_ALL_PROJECTS = "VIEW_ALL_PROJECTS",
  CREATE_PROJECT = "CREATE_PROJECT",

  // Blogs
  VIEW_ALL_BLOGS = "VIEW_ALL_BLOGS",
  CREATE_BLOG = "CREATE_BLOG",

  // Portfolios
  VIEW_ALL_PORTFOLIOS = "VIEW_ALL_PORTFOLIOS",

  // Suggestions / Moderation
  VIEW_COMPETITION_SUGGESTIONS = "VIEW_COMPETITION_SUGGESTIONS",
  REVIEW_COMPETITION_SUGGESTIONS = "REVIEW_COMPETITION_SUGGESTIONS",

  VIEW_PROJECT_SUGGESTIONS = "VIEW_PROJECT_SUGGESTIONS",
  REVIEW_PROJECT_SUGGESTIONS = "REVIEW_PROJECT_SUGGESTIONS",

  VIEW_BLOG_SUGGESTIONS = "VIEW_BLOG_SUGGESTIONS",
  REVIEW_BLOG_SUGGESTIONS = "REVIEW_BLOG_SUGGESTIONS",

  // Taxonomy
  MANAGE_CATEGORIES = "MANAGE_CATEGORIES",
  MANAGE_TECHNOLOGIES = "MANAGE_TECHNOLOGIES",
  MANAGE_TAGS = "MANAGE_TAGS",

  // Assets
  MANAGE_MEDIA = "MANAGE_MEDIA",

  // Site
  MANAGE_SITE_SETTINGS = "MANAGE_SITE_SETTINGS",
  VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS",
}
